/* [name, argv, expectedMethod, expectedPath, expectOk] */
module.exports = [
  ["whoami", ["whoami"], "GET", "/api/accounts/id", true],
  ["accounts get", ["accounts", "get", "--account", "acc_test"], "GET", "/api/accounts/acc_test", true],
  ["accounts credits", ["accounts", "credits", "--account", "acc_test"], "GET", "/api/accounts/acc_test/credits", true],
  ["accounts subscription", ["accounts", "subscription", "--account", "acc_test"], "GET", "/api/accounts/acc_test/subscription", true],
  ["accounts update", ["accounts", "update", "--name", "New"], "PATCH", "/api/accounts", true],
  ["artists list", ["artists", "list"], "GET", "/api/artists", true],
  ["artists create", ["artists", "create", "--name", "Daft Punk"], "POST", "/api/artists", true],
  ["artists update", ["artists", "update", "a1", "--label", "Columbia", "--pinned"], "PATCH", "/api/artists/a1", true],
  ["artists delete", ["artists", "delete", "a1"], "DELETE", "/api/artists/a1", true],
  ["artists fans", ["artists", "fans", "a1", "--limit", "5"], "GET", "/api/artists/a1/fans", true],
  ["artists scrape", ["artists", "scrape", "--artist", "a1"], "POST", "/api/artist/socials/scrape", true],
  ["chats list", ["chats", "list", "--artist", "a1"], "GET", "/api/chats", true],
  ["chats create", ["chats", "create", "--name", "T"], "POST", "/api/chats", true],
  ["chats update", ["chats", "update", "--chat", "c1", "--topic", "New topic"], "PATCH", "/api/chats", true],
  ["chats delete", ["chats", "delete", "--chat", "c1"], "DELETE", "/api/chats", true],
  ["chats messages", ["chats", "messages", "--chat", "c1"], "GET", "/api/chats/c1/messages", true],
  ["chats artist", ["chats", "artist", "--chat", "c1"], "GET", "/api/chats/c1/artist", true],
  ["chats compact", ["chats", "compact", "--chat", "c1", "--chat", "c2"], "POST", "/api/chats/compact", true],
  ["generate", ["generate", "--prompt", "hi", "--artist", "a1"], "POST", "/api/chat/generate", true],
  ["tasks list", ["tasks", "list"], "GET", "/api/tasks", true],
  ["tasks create", ["tasks", "create", "--title", "Daily", "--prompt", "x", "--schedule", "0 9 * * *", "--artist", "a1"], "POST", "/api/tasks", true],
  ["tasks update", ["tasks", "update", "--id", "t1", "--enabled", "false"], "PATCH", "/api/tasks", true],
  ["tasks delete", ["tasks", "delete", "--id", "t1"], "DELETE", "/api/tasks", true],
  ["tasks runs", ["tasks", "runs", "--limit", "5"], "GET", "/api/tasks/runs", true],
  ["tasks status", ["tasks", "status", "--run", "run_1"], "GET", "/api/tasks/runs", true],
  ["pulses list", ["pulses", "list"], "GET", "/api/pulses", true],
  ["pulses set", ["pulses", "set", "--active", "true"], "PATCH", "/api/pulses", true],
  ["connectors list", ["connectors", "list"], "GET", "/api/connectors", true],
  ["connectors connect", ["connectors", "connect", "--connector", "googlesheets"], "POST", "/api/connectors", true],
  ["connectors actions", ["connectors", "actions"], "GET", "/api/connectors/actions", true],
  ["connectors run", ["connectors", "run", "--action", "GMAIL_FETCH_EMAILS", "--params", '{"max_results":1}'], "POST", "/api/connectors/actions", true],
  ["connectors disconnect", ["connectors", "disconnect", "--id", "ca1"], "DELETE", "/api/connectors", true],
  ["research search", ["research", "search", "--q", "Daft Punk", "--type", "artists"], "GET", "/api/research", true],
  ["research profile", ["research", "profile", "--artist", "Daft Punk"], "GET", "/api/research/profile", true],
  ["research audience", ["research", "audience", "--artist", "x"], "GET", "/api/research/audience", true],
  ["research metrics", ["research", "metrics", "--artist", "x", "--source", "spotify"], "GET", "/api/research/metrics", true],
  ["research similar", ["research", "similar", "--artist", "x", "--genre", "high"], "GET", "/api/research/similar", true],
  ["research deep", ["research", "deep", "--query", "q"], "POST", "/api/research/deep", true],
  ["research web", ["research", "web", "--query", "news", "--max-results", "5"], "POST", "/api/research/web", true],
  ["research enrich", ["research", "enrich", "--input", "https://x", "--schema", '{"type":"object"}'], "POST", "/api/research/enrich", true],
  ["research extract", ["research", "extract", "--url", "https://x"], "POST", "/api/research/extract", true],
  ["research track-stats", ["research", "track-stats", "--isrc", "US1", "--source", "spotify"], "GET", "/api/research/track/stats", true],
  ["research track-measurements", ["research", "track-measurements", "--track", "tk1", "--window", "30d"], "GET", "/api/research/tracks/tk1/measurements", true],
  ["research snapshots", ["research", "snapshots", "--isrcs", "US1,US2"], "POST", "/api/research/snapshots", true],
  ["spotify search", ["spotify", "search", "--q", "x", "--type", "artist"], "GET", "/api/spotify/search", true],
  ["spotify top-tracks", ["spotify", "top-tracks", "--id", "z", "--market", "US"], "GET", "/api/spotify/artist/topTracks", true],
  ["spotify album", ["spotify", "album", "--id", "al1"], "GET", "/api/spotify/album", true],
  ["songs list", ["songs", "list", "--artist", "a1"], "GET", "/api/songs", true],
  ["songs presets", ["songs", "presets"], "GET", "/api/songs/analyze/presets", true],
  ["catalogs create", ["catalogs", "create", "--name", "2024"], "POST", "/api/catalogs", true],
  ["catalogs songs", ["catalogs", "songs", "--catalog", "cat1"], "GET", "/api/catalogs/songs", true],
  ["catalogs add-songs", ["catalogs", "add-songs", "--catalog", "cat1", "--songs", '[{"isrc":"US1"}]'], "POST", "/api/catalogs/songs", true],
  ["catalogs remove-songs", ["catalogs", "remove-songs", "--catalog", "cat1", "--isrc", "US1"], "DELETE", "/api/catalogs/songs", true],
  ["models list", ["models", "list"], "GET", "/api/ai/models", true],
  ["orgs list", ["orgs", "list"], "GET", "/api/organizations", true],
  ["orgs create", ["orgs", "create", "--name", "Label", "--account", "acc_test"], "POST", "/api/organizations", true],
  ["orgs add-artist", ["orgs", "add-artist", "--artist", "a1", "--org", "o1"], "POST", "/api/organizations/artists", true],
  ["workspaces create", ["workspaces", "create", "--name", "Q1"], "POST", "/api/workspaces", true],
  ["templates list", ["templates", "list"], "GET", "/api/agents/templates", true],
  ["templates create", ["templates", "create", "--title", "Recap", "--description", "Weekly recap of streams", "--prompt", "Produce a weekly streaming recap report", "--tags", "a,b"], "POST", "/api/agents/templates", true],
  ["templates favorite", ["templates", "favorite", "tpl1"], "PUT", "/api/agents/templates/tpl1/favorite", true],
  ["templates delete", ["templates", "delete", "tpl1"], "DELETE", "/api/agents/templates/tpl1", true],
  ["sessions create", ["sessions", "create", "--title", "Build"], "POST", "/api/sessions", true],
  ["sessions get", ["sessions", "get", "s1"], "GET", "/api/sessions/s1", true],
  ["sessions update", ["sessions", "update", "s1", "--status", "completed"], "PATCH", "/api/sessions/s1", true],
  ["sandboxes list", ["sandboxes", "list"], "GET", "/api/sandboxes", true],
  ["sandboxes file", ["sandboxes", "file", "--path", "README.md"], "GET", "/api/sandboxes/file", true],
  ["sandboxes setup", ["sandboxes", "setup"], "POST", "/api/sandboxes/setup", true],
  ["content templates", ["content", "templates"], "GET", "/api/content/templates", true],
  ["content template", ["content", "template", "tpl"], "GET", "/api/content/templates/tpl", true],
  ["content caption", ["content", "caption", "--topic", "tour"], "POST", "/api/content/caption", true],
  ["content image", ["content", "image", "--prompt", "art", "--num", "2"], "POST", "/api/content/image", true],
  ["content transcribe", ["content", "transcribe", "--audio", "https://a.mp3"], "POST", "/api/content/transcribe", true],
  ["content edit", ["content", "edit", "--video", "https://v.mp4", "--template", "cut"], "PATCH", "/api/content", true],
  ["notifications", ["notifications", "--subject", "Hi", "--text", "Body"], "POST", "/api/notifications", true],
  // Fast-fail validation cases (must exit non-zero with Error:, no network call)
  ["ERR generate no prompt", ["generate"], null, null, false],
  ["ERR track-stats no id", ["research", "track-stats", "--source", "spotify"], null, null, false],
  ["ERR accounts update empty", ["accounts", "update"], null, null, false],
  ["ERR catalogs create empty", ["catalogs", "create"], null, null, false],
  ["ERR tasks create missing req", ["tasks", "create", "--title", "x"], null, null, false],
  ["ERR research lookup no args", ["research", "lookup"], null, null, false],
  ["ERR research snapshots no scope", ["research", "snapshots"], null, null, false],
];
